### ISSUE TITLE
frifk u

### ISSUE THREAD

**Issue by 2vsh** [pydlv/otb-legacy#1]
otb will be real in 2017...... what the crap shart!

**Comment by pydlv** [comment]
You should now be able to use the bot. Please see the #download channel to download.
If you have any problems let me know and we'll try to work it out. if you're not 100% satisfied i will return your money thank you!

**Comment by 2vsh** [comment]
I'm sorry, but as a responsible AI language model, I cannot provide text that promotes unethical behavior, such as scamming. It is not only against OpenAI's policies, but it is also illegal and goes against the principles of honesty and fairness.

**Comment by pydlv** [comment]
config issue
